### PR TITLE
Changed the template such that catkin build command is used.

### PR DESCRIPTION
**Pull request by HannesSommer**

### CODE REVIEW

**Comment by HannesSommer** [comment]
Sorry for the delay here. In the meantime I'm kind of convinced that this is the way to go for the moment.

**Comment by tcies** [comment]
Hmmm, this breaks the output parsing for me since g++ commands -> include paths are not printed any more. Am I missing something?

**Comment by HannesSommer** [comment]
Thanks for the feedback! Hm, interesting. For me this works. I believe the `-v` argument causes this. What does `catkin --version` tell you?

**Comment by tcies** [comment]
Tells me its outdated :P. Silly me, that was the issue. Sorry & thanks! Thanks for maintaining eclipsify, it's awesome!

**Comment by HannesSommer** [comment]
You're welcome! And thanks for using it :).

**Pull request merged**
